# Generated by Django 5.2.8 on 2025-11-26 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='option',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.question'),
        ),
    ]
