# Generated by Django 5.2.8 on 2025-11-26 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_remove_exam_option_option_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.option'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
