# Generated by Django 5.2.8 on 2025-11-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_review_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_name',
            new_name='sub_category_name',
        ),
    ]
