# Generated by Django 5.2.8 on 2025-11-28 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_rename_category_name_subcategory_sub_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
