# Generated by Django 5.2.8 on 2025-11-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_course_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams_questions', to='mysite.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='mysite.option'),
        ),
    ]
