# Generated by Django 5.2.8 on 2025-11-29 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_assignment_description_en_assignment_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_name_en',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_name_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_name_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_name_ru',
        ),
        migrations.AlterField(
            model_name='course',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
